### ISSUE TITLE
Decide between cpy.Machine and cpy.Copier

### ISSUE THREAD

**Issue by neild** [google/go-cpy#2]
`cpy.Machine` avoids repetition and sounds like a photocopier.
`cpy.Copier` is fairly conventional Go naming.

One last chance to pick between the two before 1.0.

**Comment by dsnet** [comment]
Let's just go with `cpy.Copier`:
1. It's more idiomatic. I was probably being too cute when I named it `Machine`
2. The naming is fairly inconsequential. You almost always construct it with `cpy.New` and rarely reference the type by name.
